#include "codeinput.h"
#include "ctrlcode.h"
#include "kkconv.h"
#include "romkan.h"
#include "skk.h"
#include "zenkakualpha.h"
#include <stdio.h>

void
Skk::initialize(const std::function<void(std::string_view)>& output)
{
  m_output = output;

  auto thru = [self = this](char c, bool) { self->thru(c); };

  auto& NormalKeymap = m_keymaps[KeymapTypes::Normal];
  NormalKeymap.DefaultFunc = thru;
  NormalKeymap.Keymap[CTRL_T] = [self = this](auto, auto) { self->toKana(); };

  auto& KanaKeymap = m_keymaps[KeymapTypes::Kana];
  KanaKeymap.DefaultFunc = romkan::flthru;
  KanaKeymap.Keymap = {
    { CTRL_H, [&output](auto s, auto) { output(romkan::kanaBS(s)); } },
    { '!', zenkakualpha::iZenAl },
    { ',', zenkakualpha::iZenAl },
    { '-', zenkakualpha::iZenEx },
    { '.', zenkakualpha::iZenAl },
    { '/', [self = this](auto c, auto) { kkBegA(self, c); } },
    { ':', zenkakualpha::iZenAl },
    { ';', zenkakualpha::iZenAl },
    { '?', zenkakualpha::iZenAl },
    { 'A', [self = this](auto c, auto) { kkBegV(self, c); } },
    { 'B', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'C', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'D', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'E', [self = this](auto c, auto) { kkBegV(self, c); } },
    { 'F', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'G', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'H', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'I', [self = this](auto c, auto) { kkBegV(self, c); } },
    { 'J', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'K', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'L', [self = this](auto, auto) { self->toZenA(); } },
    { 'M', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'N', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'O', [self = this](auto c, auto) { kkBegV(self, c); } },
    { 'P', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'Q', [self = this](auto, auto) { self->kkBeg(); } },
    { 'R', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'S', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'T', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'U', [self = this](auto c, auto) { kkBegV(self, c); } },
    { 'V', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'W', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'X', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'Y', [self = this](auto c, auto) { kkBegC(self, c); } },
    { 'Z', [self = this](auto c, auto) { kkBegC(self, c); } },
    { '[', zenkakualpha::iZenEx },
    { '\\', [self = this](auto, auto) { g_codeinput.inputCode(self); } },
    { ']', zenkakualpha::iZenEx },
    { 'a', [&output](auto s, bool) { output(romkan::iKanaV(s)); } },
    { 'b', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'c', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'd', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'e', [&output](auto s, bool) { output(romkan::iKanaV(s)); } },
    { 'f', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'g', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'h', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'i', [&output](auto s, bool) { output(romkan::iKanaV(s)); } },
    { 'j', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'k', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'l', [self = this](auto, auto) { self->toAsc(); } },
    { 'm', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'n', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'o', [&output](auto s, bool) { output(romkan::iKanaV(s)); } },
    { 'p', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'q',
      [self = this](auto, auto) {
        romkan::tglK(self);
        ;
      } },
    { 'r', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 's', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 't', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'u', [&output](auto s, bool) { output(romkan::iKanaV(s)); } },
    { 'v', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'w', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'x', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'y', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
    { 'z', [&output](auto s, bool) { output(romkan::iKanaC(s)); } },
  };

  auto& ZenkakuKeymap = m_keymaps[KeymapTypes::Zenkaku];
  ZenkakuKeymap.DefaultFunc = thru;
  ZenkakuKeymap.Keymap = {
    { ' ', zenkakualpha::iZenAl },  { '!', zenkakualpha::iZenAl },
    { '"', zenkakualpha::iZenAl },  { '#', zenkakualpha::iZenAl },
    { '$', zenkakualpha::iZenAl },  { '%', zenkakualpha::iZenAl },
    { '&', zenkakualpha::iZenAl },  { '\'', zenkakualpha::iZenAl },
    { '(', zenkakualpha::iZenAl },  { ')', zenkakualpha::iZenAl },
    { '*', zenkakualpha::iZenAl },  { '+', zenkakualpha::iZenAl },
    { '}', zenkakualpha::iZenAl },  { '-', zenkakualpha::iZenAl },
    { '.', zenkakualpha::iZenAl },  { '/', zenkakualpha::iZenAl },
    { '0', zenkakualpha::iZenAl },  { '1', zenkakualpha::iZenAl },
    { '2', zenkakualpha::iZenAl },  { '3', zenkakualpha::iZenAl },
    { '4', zenkakualpha::iZenAl },  { '5', zenkakualpha::iZenAl },
    { '6', zenkakualpha::iZenAl },  { '7', zenkakualpha::iZenAl },
    { '8', zenkakualpha::iZenAl },  { '9', zenkakualpha::iZenAl },
    { ':', zenkakualpha::iZenAl },  { ';', zenkakualpha::iZenAl },
    { '<', zenkakualpha::iZenAl },  { '=', zenkakualpha::iZenAl },
    { '>', zenkakualpha::iZenAl },  { '?', zenkakualpha::iZenAl },
    { '@', zenkakualpha::iZenAl },  { 'A', zenkakualpha::iZenAl },
    { 'B', zenkakualpha::iZenAl },  { 'C', zenkakualpha::iZenAl },
    { 'D', zenkakualpha::iZenAl },  { 'E', zenkakualpha::iZenAl },
    { 'F', zenkakualpha::iZenAl },  { 'G', zenkakualpha::iZenAl },
    { 'H', zenkakualpha::iZenAl },  { 'I', zenkakualpha::iZenAl },
    { 'J', zenkakualpha::iZenAl },  { 'K', zenkakualpha::iZenAl },
    { 'L', zenkakualpha::iZenAl },  { 'M', zenkakualpha::iZenAl },
    { 'N', zenkakualpha::iZenAl },  { 'O', zenkakualpha::iZenAl },
    { 'P', zenkakualpha::iZenAl },  { 'Q', zenkakualpha::iZenAl },
    { 'R', zenkakualpha::iZenAl },  { 'S', zenkakualpha::iZenAl },
    { 'T', zenkakualpha::iZenAl },  { 'U', zenkakualpha::iZenAl },
    { 'V', zenkakualpha::iZenAl },  { 'W', zenkakualpha::iZenAl },
    { 'X', zenkakualpha::iZenAl },  { 'Y', zenkakualpha::iZenAl },
    { 'Z', zenkakualpha::iZenAl },  { '[', zenkakualpha::iZenAl },
    { '\\', zenkakualpha::iZenAl }, { ']', zenkakualpha::iZenAl },
    { '^', zenkakualpha::iZenAl },  { '_', zenkakualpha::iZenAl },
    { '`', zenkakualpha::iZenAl },  { 'a', zenkakualpha::iZenAl },
    { 'b', zenkakualpha::iZenAl },  { 'c', zenkakualpha::iZenAl },
    { 'd', zenkakualpha::iZenAl },  { 'e', zenkakualpha::iZenAl },
    { 'f', zenkakualpha::iZenAl },  { 'g', zenkakualpha::iZenAl },
    { 'h', zenkakualpha::iZenAl },  { 'i', zenkakualpha::iZenAl },
    { 'j', zenkakualpha::iZenAl },  { 'k', zenkakualpha::iZenAl },
    { 'l', zenkakualpha::iZenAl },  { 'm', zenkakualpha::iZenAl },
    { 'n', zenkakualpha::iZenAl },  { 'o', zenkakualpha::iZenAl },
    { 'p', zenkakualpha::iZenAl },  { 'q', zenkakualpha::iZenAl },
    { 'r', zenkakualpha::iZenAl },  { 's', zenkakualpha::iZenAl },
    { 't', zenkakualpha::iZenAl },  { 'u', zenkakualpha::iZenAl },
    { 'v', zenkakualpha::iZenAl },  { 'w', zenkakualpha::iZenAl },
    { 'x', zenkakualpha::iZenAl },  { 'y', zenkakualpha::iZenAl },
    { 'z', zenkakualpha::iZenAl },  { '{', zenkakualpha::iZenAl },
    { '|', zenkakualpha::iZenAl },  { '}', zenkakualpha::iZenAl },
    { '~', zenkakualpha::iZenAl },
  };

  auto& KanjiInputKeymap = m_keymaps[KeymapTypes::KanjiInput];
  KanjiInputKeymap.DefaultFunc = nulcmd;
  KanjiInputKeymap.Keymap = {
    { CTRL_G, [self = this](auto c, auto) { kfCancel(self, c); } },
    { CTRL_H, kfBS },
    { CTRL_M, [self = this](auto c, auto) { kfFixThru(self, c); } },
    { ' ', [self = this](auto c, auto) { kkconv(self, c); } },
    { '!', kZenAl },
    { '"', kfthru },
    { '#', kfthru },
    { '$', kfthru },
    { '%', kfthru },
    { '^', kfthru },
    { '\'', kfthru },
    { '(', kfthru },
    { ')', kfthru },
    { '*', kfthru },
    { '+', kfthru },
    { '}', kZenAl },
    { '-', kZenEx },
    { '.', kZenAl },
    { '/', kfthru },
    { '0', kfthru },
    { '1', kfthru },
    { '2', kfthru },
    { '3', kfthru },
    { '4', kfthru },
    { '5', kfthru },
    { '6', kfthru },
    { '7', kfthru },
    { '8', kfthru },
    { '9', kfthru },
    { ':', kZenAl },
    { ';', kZenAl },
    { '<', [self = this](auto c, auto) { stPrefixCv(self, c); } },
    { '=', kfthru },
    { '>', [self = this](auto c, auto) { stPrefixCv(self, c); } },
    { '?', [self = this](auto c, auto) { stPrefixCv(self, c); } },
    { '@', kfthru },
    { 'A', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'B', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'C', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'D', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'E', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'F', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'G', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'H', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'I', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'J', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'K', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'L', [self = this](auto c, auto) { kfFixToZenA(self, c); } },
    { 'M', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'N', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'O', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'P', [self = this](auto c, auto) { kOkuri(self, c); } },
    //
    { 'R', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'S', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'T', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'U', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'V', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'W', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'X', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'Y', [self = this](auto c, auto) { kOkuri(self, c); } },
    { 'Z', [self = this](auto c, auto) { kOkuri(self, c); } },
    { '[', kZenEx },
    { '\\', kfthru },
    { ']', kZenEx },
    { '^', kfthru },
    { '_', kfthru },
    { '`', kfthru },
    { 'a', kKanaV },
    { 'b', kKanaC },
    { 'c', kKanaC },
    { 'd', kKanaC },
    { 'e', kKanaV },
    { 'f', kKanaC },
    { 'g', kKanaC },
    { 'h', kKanaC },
    { 'i', kKanaV },
    { 'j', kKanaC },
    { 'k', kKanaC },
    { 'l', [self = this](auto c, auto) { kfFixToAsc(self, c); } },
    { 'm', kKanaC },
    { 'n', kKanaC },
    { 'o', kKanaV },
    { 'p', kKanaC },
    { 'q', [self = this](auto c, auto) { h2kkana(self, c); } },
    { 'r', kKanaC },
    { 's', kKanaC },
    { 't', kKanaC },
    { 'u', kKanaV },
    { 'v', kKanaC },
    { 'w', kKanaC },
    { 'x', kKanaC },
    { 'y', kKanaC },
    { 'z', kKanaC },
    { '{', kfthru },
    { '|', kfthru },
    { '}', kfthru },
    { '~', kfthru },
  };

  auto& OkuriInputKeymap = m_keymaps[KeymapTypes::OkuriInput];
  OkuriInputKeymap.DefaultFunc = nulcmd;
  OkuriInputKeymap.Keymap = {
    { CTRL_G, [self = this](auto, auto) { cancelOkuri(self); } },
    { CTRL_H, [self = this](auto c, auto) { okuriBS(self, c); } },
    { CTRL_M, [self = this](auto c, auto) { okfFixThru(self, c); } },
    { ' ', [self = this](auto c, auto) { okfFix(self, c); } },
    { 'A', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'B', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'C', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'D', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'E', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'F', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'G', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'H', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'I', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'J', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'K', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'L', [self = this](auto c, auto o) { okfFixToZenA(self, c); } },
    { 'M', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'N', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'O', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'P', [self = this](auto c, auto o) { okKanaC(c, o); } },
    //
    { 'R', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'S', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'T', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'U', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'V', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'W', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'X', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'Y', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'Z', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'a', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'b', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'c', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'd', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'e', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'f', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'g', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'h', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'i', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'j', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'k', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'l', [self = this](auto c, auto o) { okfFixToAsc(self, c); } },
    { 'm', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'n', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'o', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'p', [self = this](auto c, auto o) { okKanaC(c, o); } },
    //
    { 'r', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 's', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 't', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'u', [self = this](auto c, auto o) { okKanaV(self, c, o); } },
    { 'v', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'w', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'x', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'y', [self = this](auto c, auto o) { okKanaC(c, o); } },
    { 'z', [self = this](auto c, auto o) { okKanaC(c, o); } },
  };

  auto& KAlphaInputKeymap = m_keymaps[KeymapTypes::KAlphaInput];
  KAlphaInputKeymap.DefaultFunc = nulcmd;
  KAlphaInputKeymap.Keymap = {
    { CTRL_G, [self = this](auto c, auto) { kfCancel(self, c); } },
    { CTRL_H, kaBS },
    { ' ', [self = this](auto c, auto) { kkconv(self, c); } },
    { '!', kalpha },
    { '"', kalpha },
    { '#', kalpha },
    { '$', kalpha },
    { '%', kalpha },
    { '^', kalpha },
    { '\'', kalpha },
    { '(', kalpha },
    { ')', kalpha },
    { '*', kalpha },
    { '+', kalpha },
    { '}', kalpha },
    { '-', kalpha },
    { '.', kalpha },
    { '/', kalpha },
    { '0', kalpha },
    { '1', kalpha },
    { '2', kalpha },
    { '3', kalpha },
    { '4', kalpha },
    { '5', kalpha },
    { '6', kalpha },
    { '7', kalpha },
    { '8', kalpha },
    { '9', kalpha },
    { ':', kalpha },
    { ';', kalpha },
    { '<', kalpha },
    { '=', kalpha },
    { '>', kalpha },
    { '?', kalpha },
    { '@', kalpha },
    { 'A', kalpha },
    { 'B', kalpha },
    { 'C', kalpha },
    { 'D', kalpha },
    { 'E', kalpha },
    { 'F', kalpha },
    { 'G', kalpha },
    { 'H', kalpha },
    { 'I', kalpha },
    { 'J', kalpha },
    { 'K', kalpha },
    { 'L', kalpha },
    { 'M', kalpha },
    { 'N', kalpha },
    { 'O', kalpha },
    { 'P', kalpha },
    { 'Q', kalpha },
    { 'R', kalpha },
    { 'S', kalpha },
    { 'T', kalpha },
    { 'U', kalpha },
    { 'V', kalpha },
    { 'W', kalpha },
    { 'X', kalpha },
    { 'Y', kalpha },
    { 'Z', kalpha },
    { '[', kalpha },
    { '\\', kalpha },
    { ']', kalpha },
    { '^', kalpha },
    { '_', kalpha },
    { '`', kalpha },
    { 'a', kalpha },
    { 'b', kalpha },
    { 'c', kalpha },
    { 'd', kalpha },
    { 'e', kalpha },
    { 'f', kalpha },
    { 'g', kalpha },
    { 'h', kalpha },
    { 'i', kalpha },
    { 'j', kalpha },
    { 'k', kalpha },
    { 'l', kalpha },
    { 'm', kalpha },
    { 'n', kalpha },
    { 'o', kalpha },
    { 'p', kalpha },
    { 'q', kalpha },
    { 'r', kalpha },
    { 's', kalpha },
    { 't', kalpha },
    { 'u', kalpha },
    { 'v', kalpha },
    { 'w', kalpha },
    { 'x', kalpha },
    { 'y', kalpha },
    { 'z', kalpha },
    { '{', kalpha },
    { '|', kalpha },
    { '}', kalpha },
    { DEL_CODE, kalpha },
  };

  auto& SelectionKeymap = m_keymaps[KeymapTypes::Selection];
  SelectionKeymap.DefaultFunc = [self = this](auto c, auto) {
    fxthru(self, c);
  };
  SelectionKeymap.Keymap = {
    { CTRL_G, [self = this](auto c, auto) { cancelSel(self, c); } },
    { CTRL_T, [self = this](auto, auto) { fixIt(self); } },
    { ' ', [](auto, auto) { nxCand(); } },
    { 'x', [self = this](auto, auto) { pvCand(self); } },
    { '>', [self = this](auto c, auto) { stSuffix(self, c); } },
    { '?', [self = this](auto c, auto) { stSuffix(self, c); } },
    { '<', [self = this](auto c, auto) { stSuffix(self, c); } },
    { EXTRA_CODE, [self = this](auto c, auto) { thruFixItToAsc(self, c); } },
  };

  auto& CodeInputKeymap = m_keymaps[KeymapTypes::CodeInput];
  CodeInputKeymap.DefaultFunc = nulcmd;
  CodeInputKeymap.Keymap = {
    { CTRL_C, [self = this](auto, auto) { self->cancelCode(); } },
    { CTRL_G, [self = this](auto, auto) { self->cancelCode(); } },
    { CTRL_J, [self = this](auto, auto) { g_codeinput.enterCode(self); } },
    { CTRL_M, [self = this](auto, auto) { g_codeinput.enterCode(self); } },
    { CTRL_T, [self = this](auto, auto) { self->toKana(); } },
    { '0', [](auto c, auto) { g_codeinput.codein(c); } },
    { '1', [](auto c, auto) { g_codeinput.codein(c); } },
    { '2', [](auto c, auto) { g_codeinput.codein(c); } },
    { '3', [](auto c, auto) { g_codeinput.codein(c); } },
    { '4', [](auto c, auto) { g_codeinput.codein(c); } },
    { '5', [](auto c, auto) { g_codeinput.codein(c); } },
    { '6', [](auto c, auto) { g_codeinput.codein(c); } },
    { '7', [](auto c, auto) { g_codeinput.codein(c); } },
    { '8', [](auto c, auto) { g_codeinput.codein(c); } },
    { '9', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'A', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'B', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'C', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'D', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'E', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'F', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'a', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'b', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'c', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'd', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'e', [](auto c, auto) { g_codeinput.codein(c); } },
    { 'f', [](auto c, auto) { g_codeinput.codein(c); } },
  };
}
